#!/bin/bash                                                                     

echo "Enter your date(%Y-%m-%d):"

read my_date
DATE=`date +%Y-%m-%d`
echo $DATE
if [ $my_date==$DATE ];                                           
        echo "Confirmed, they are the same!"
    else
        echo "Confirmed, they are NOT the same!"
fi


